export const title = "Protocol Revenue Tracker";
export const description = "Protocol Revenue Tracker is a Mini App that monitors revenue and fees generated by DeFi protocols in real time. Track daily, weekly, and monthly earnings, compare protocol performance, and receive alerts when revenue spikes or drops significantly.";
export const url = process.env.NEXT_PUBLIC_URL;
